title: Programming Blog Adventure
author: John Hayes
email: jdhayes.linux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my Programming Blog Adventure. I will blog about my adventures
  through programming, Docker, Python, Azure, Google Cloud and AWS.

# social links
twitter_username: HayesJohnD # DO NOT include the @ character, or else the build will fail!
github_username:  just-linux # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
