title: Programming Adventure Blog
author: John Hayes
email: jdhayes.linux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is to detail my adventures in programming. I will be 
  going through the world of Python, Docker, Azure and perhaps more.

# social links
twitter_username: HayesJohnD # DO NOT include the @ character, or else the build will fail!
github_username:  just-linux # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
